mysite/blog/urls.py
from django.urls import path

from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('tag/<slug:tag_slug>', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('search/', views.post_search, name='post_search')
]

mysite/mysite/urls.py
from django.urls import path, include

from django.contrib import admin
from django.contrib.sitemaps.views import sitemap

from blog.views import index_redirect
from blog.sitemaps import PostsSiteMap

sitemaps = {
    'posts': PostsSiteMap,
}

urlpatterns = [
    path('', index_redirect, name='index'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, 
         name='django.contrib.sitemaps.views.sitemap')
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        # return super(PublishedManager, self).get_queryset().filter(status='published')
        return super().get_queryset().filter(status='published')
        

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(
        max_length=250,
        unique_for_date='publish',
    )
    author = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='blog_posts',
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='draft',
    )
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'blog:post_detail',
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug,
            ],
        )

    class Meta:
        ordering=('-publish',)


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment on {self.post} by {self.name}'

mysite/blog/forms.py
from django import forms
from .models import Comment, Post

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    post = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Post.objects.all(),
        disabled=True,
    )

    class Meta:
        model = Comment
        fields = ('post', 'name', 'email', 'body')

class SearchForm(forms.Form):
    query = forms.CharField(max_length=250)

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import (
    Paginator,
    EmptyPage,
    PageNotAnInteger,
)
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count, Q
from django.contrib.postgres.search import SearchVector

from taggit.models import Tag

from .models import Post, Comment
from .forms import (
    EmailPostForm, 
    CommentForm, 
    SearchForm,
)

PAGINATE_BY = 5

def post_list(request, tag_slug=None):
    object_list = Post.published.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, PAGINATE_BY)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        #If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        #If page is out of range deliver last page of resuts
        posts = paginator.page(paginator.num_pages)
    return render(
        request,
        'blog/post/list.html',
        {
            'page': page,
            'posts': posts,
            'tag': tag,
        },
    )

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name= 'posts'
    paginate_by = PAGINATE_BY
    template_name = 'blog/post/list.html'

def post_detail(request, year, month, day, post):
    #We can be sure, that we'll get a single post, because we set
    #'unique_for_date' parameter in slug field definition to use
    #'publish' date
    post = get_object_or_404(
        Post, slug=post, status='published', publish__year=year,
        publish__month=month, publish__day=day
    )

    #List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment=None

    if request.method == "POST":
        #A comment was posted
        
        comment_form = CommentForm(initial={'post': post.id}, data=request.POST)
        if comment_form.is_valid():
            #Create Comment object, but don't save to the database yet
            new_comment = comment_form.save()
            #Assign current post to the comment
            # new_comment.post = post
            #Save the comment
            # new_comment.save()
    else:
        comment_form = CommentForm(initial={'post': post.id})

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                                  .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                 .order_by('-same_tags','-publish')[:4]

    return render(
        request,
        'blog/post/detail.html',
        {
            'post': post,
            'comments': comments,
            'new_comment': new_comment,
            'comment_form': comment_form,
            'similar_posts': similar_posts,
        }
    )

def post_share(request, post_id):
    # Get post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == "POST":
        #Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            #Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} ({cd['email']}) recomments you reading"
            message = f"Read '{post.title}' at {post_url}\n\n"\
                      f"{cd['name']}'s comments: {cd['comments']}"
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True

    else:
        form = EmailPostForm()

    return render(
        request, 
        'blog/post/share.html',
        {
            'post': post,
            'form': form,
            'sent': sent,
        })

def index_redirect(request):
    return redirect('blog:post_list')


def post_search(request):
    form = SearchForm()

    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.filter(
                Q(title__icontains=query) | Q(body__icontains=query))
    
    return render(
        request,
        'blog/post/search.html',
        {
            'form': form,
            'query': query,
            'results': results,
        }
    )

mysite/blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}
            {% endblock %}
        </title>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>My Blog</h2>
        <p>This is my blog. It  contains {% total_posts %} posts so far.</p>
        <h2><a href="{% url 'blog:post_search' %}">Search</a></h2>
        <p><a href="{% url 'blog:post_feed' %}">My RSS feed.</a></p>
        <h3>Latest Posts:</h3>
        {% show_latest_posts 3 %}
        <h3>Hottest Posts:</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
        {% for post in most_commented_posts %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
        {% endfor %}
        </ul>
    </div>
</body>
</html>

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <h1>
        <a href="{% url 'blog:post_list' %}">
            &#8592;{{ post.title }}
        </a>
    </h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p class="tags">
        Tags: 
        {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag_slug=tag.slug %}">
                {{ tag.name }}
            </a>
            {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>
    <a href="{% url 'blog:post_share' post_id=post.id %}">Share this post</a>
    <h2>Similar Posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        There're no similar posts yet.
    {% endfor %}
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There're no comments yet.</p>
    {% endfor %}
    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add new comment</h2>
        <form action="" method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add Comment"></p>
        </form>
    {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/latest.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}
    My Blog
{% endblock %}

{% block content %}
    <h1><a href="{% url 'blog:post_list' %}">My Blog</a></h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}" (<a href="{% url 'blog:post_list' %}">Show all</a>)</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <div class="date">
            Published {{ post.publish }} by {{ post.author }}
        </div>
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

mysite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}

{% block title %}
    Search
{% endblock %}

{% block content %}
        <h1>Search for posts</h1>
        <form action="." method="get">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Search">
        </form> 
        {% if query %}
        <div style="display: float: left">
            <h1>Posts containing {{ query }}</h1>
            <h3>
                {% with results.count as total_results %}
                    Found {{ total_results }} result{{ total_results|pluralize }}
                {% endwith %}
            </h3>
            <ul>
                {% for post in results %}
                <h4>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h4>
                {{ post.body|truncatewords:5 }}
                {% empty %}
                <p>Nothing found.</p>
                {% endfor %}
                <p>
                    <a href="{% url 'blog:post_search' %}">Search again</a>
                </p>
            </ul>
        </div>
    {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}
    Share a post
{% endblock %}

{% block content %}
<div>
    <a href="{% url 'blog:post_detail' year=post.publish.year month=post.publish.month day=post.publish.day post=post.slug %}">Return</a>
</div>
    {% if sent %}
        <h1>Email successfully sent.</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by email</h1>        
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}

mysite/blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>